[lib]
proc-macro = true

[package]
name = "tmtc-system-macros"
version = "0.1.0"
edition = "2024"

[features]
serde = []

[dependencies]
heck = "0.5.0"
syn = { version = "2.0", features = ["full"]}
quote = "1.0"
proc-macro2 = "1.0"
